pragma Ada_2022;

with Ada.Characters.Handling; use Ada.Characters.Handling;

package body Lexical_Analysis is

   -- Internal Helper: Checks for standard whitespace characters
   function Is_Whitespace (C : Character) return Boolean is
   begin
      return C = ' ' or C = ASCII.HT or C = ASCII.LF or C = ASCII.CR;
   end Is_Whitespace;

   -- Internal Helper: Strips leading space generated by Ada 'Image attribute
   function Trim_Space (S : String) return String is
   begin
      if S'Length > 0 and then S (S'First) = ' ' then
         return S (S'First + 1 .. S'Last);
      else
         return S;
      end if;
   end Trim_Space;

   -----------------------------------------------------------------------------
   -- Phase A: Scanner Variant
   -----------------------------------------------------------------------------
   procedure Extract_Lexeme
     (Input     : String;
      Start_Pos : Positive;
      Lex_Start : out Positive;
      Lex_End   : out Natural)
   is
      Idx : Positive := Start_Pos;
   begin
      -- Skip whitespace
      while Idx <= Input'Last and then Is_Whitespace (Input (Idx)) loop
         Idx := Idx + 1;
      end loop;

      if Idx > Input'Last then
         Lex_Start := Start_Pos;
         Lex_End   := 0; -- Indicates no lexeme found (EOF)
         return;
      end if;

      Lex_Start := Idx;

      -- Lexeme categorization based on the first character
      if Is_Letter (Input (Idx)) then
         -- Scan Identifier or Keyword
         while Idx < Input'Last and then Is_Alphanumeric (Input (Idx + 1)) loop
            Idx := Idx + 1;
         end loop;
         Lex_End := Idx;

      elsif Is_Digit (Input (Idx)) then
         -- Scan Integer Literal
         while Idx < Input'Last and then Is_Digit (Input (Idx + 1)) loop
            Idx := Idx + 1;
         end loop;
         Lex_End := Idx;

      elsif Input (Idx) = '<' or Input (Idx) = '>' or 
            Input (Idx) = '=' or Input (Idx) = '!' then
         -- Scan Operator using Maximal Munch strategy for multi-char operators
         if Idx < Input'Last and then Input (Idx + 1) = '=' then
            Lex_End := Idx + 1;
         else
            Lex_End := Idx;
         end if;
         
      elsif Input (Idx) = '+' or Input (Idx) = '-' or 
            Input (Idx) = '*' or Input (Idx) = '/' then
         -- Single character operators
         Lex_End := Idx;
         
      elsif Input (Idx) = '(' or Input (Idx) = ')' or 
            Input (Idx) = ';' or Input (Idx) = ',' then
         -- Punctuation
         Lex_End := Idx;
         
      else
         -- Unknown/Error character fallback (returns 1-char lexeme)
         Lex_End := Idx;
      end if;
   end Extract_Lexeme;

   -----------------------------------------------------------------------------
   -- Phase B: Evaluator Variant
   -----------------------------------------------------------------------------
   function Evaluate_Lexeme
     (Input     : String;
      Lex_Start : Positive;
      Lex_End   : Natural;
      Line      : Positive;
      Column    : Positive) return Token
   is
      Result : Token;
   begin
      Result.Line   := Line;
      Result.Column := Column;

      if Lex_End = 0 or else Lex_Start > Lex_End then
         Result.Kind := Tk_End_Of_Input;
         Result.Text := To_Unbounded_String ("");
         return Result;
      end if;

      declare
         Lexeme_Str : constant String := Input (Lex_Start .. Lex_End);
         C          : constant Character := Lexeme_Str (Lexeme_Str'First);
      begin
         Result.Text := To_Unbounded_String (Lexeme_Str);

         if Is_Letter (C) then
            if Is_Keyword (Lexeme_Str) then
               Result.Kind := Tk_Keyword;
            else
               Result.Kind := Tk_Identifier;
            end if;
         elsif Is_Digit (C) then
            Result.Kind := Tk_Integer_Literal;
         elsif C = '<' or C = '>' or C = '=' or C = '!' or 
               C = '+' or C = '-' or C = '*' or C = '/' then
            Result.Kind := Tk_Operator;
         elsif C = '(' or C = ')' or C = ';' or C = ',' then
            Result.Kind := Tk_Punctuation;
         else
            Result.Kind := Tk_Error;
         end if;
      end;

      return Result;
   end Evaluate_Lexeme;

   -----------------------------------------------------------------------------
   -- Variant 3: Lazy Lexer Implementation (State Machine)
   -----------------------------------------------------------------------------
   function Initialize (Input : String) return Lexer is
      Result : Lexer;
   begin
      Result.Input_Text   := To_Unbounded_String (Input);
      Result.Current_Pos  := 1;
      Result.Current_Line := 1;
      Result.Current_Col  := 1;
      return Result;
   end Initialize;

   procedure Next_Token (Self : in out Lexer; Tok : out Token) is
      Len : constant Natural := Length (Self.Input_Text);
      C   : Character;
      Start_Idx : Positive;
      End_Idx   : Natural;
   begin
      -- Advanced whitespace skipping with line and column tracking
      while Self.Current_Pos <= Len loop
         C := Element (Self.Input_Text, Self.Current_Pos);
         if C = ASCII.LF then
            Self.Current_Line := Self.Current_Line + 1;
            Self.Current_Col  := 1;
         elsif C = ' ' or C = ASCII.HT or C = ASCII.CR then
            Self.Current_Col := Self.Current_Col + 1;
         else
            exit; -- End of whitespace block
         end if;
         Self.Current_Pos := Self.Current_Pos + 1;
      end loop;

      -- Check if End of File was reached
      if Self.Current_Pos > Len then
         Tok.Kind   := Tk_End_Of_Input;
         Tok.Text   := To_Unbounded_String ("");
         Tok.Line   := Self.Current_Line;
         Tok.Column := Self.Current_Col;
         return;
      end if;

      declare
         Input_Str : constant String := To_String (Self.Input_Text);
      begin
         -- Utilize Scanner to find bounds
         Extract_Lexeme (Input_Str, Self.Current_Pos, Start_Idx, End_Idx);

         if End_Idx = 0 then
            Tok.Kind   := Tk_End_Of_Input;
            Tok.Text   := To_Unbounded_String ("");
            Tok.Line   := Self.Current_Line;
            Tok.Column := Self.Current_Col;
            return;
         end if;

         -- Utilize Evaluator to construct the Token
         Tok := Evaluate_Lexeme
           (Input_Str, Start_Idx, End_Idx, Self.Current_Line, Self.Current_Col);

         -- Advance state for the next iterator call
         Self.Current_Pos := End_Idx + 1;
         Self.Current_Col := Self.Current_Col + (End_Idx - Start_Idx + 1);
      end;
   end Next_Token;

   -----------------------------------------------------------------------------
   -- Variant 1: Eager Tokenization Strategy
   -----------------------------------------------------------------------------
   function Tokenize_Eager (Input : String) return Token_Array is
      L          : Lexer := Initialize (Input);
      Tok        : Token;
      Count      : Natural := 0;
      Max_Tokens : constant Positive := Input'Length + 1;
      Temp_Arr   : Token_Array (1 .. Max_Tokens);
   begin
      loop
         Next_Token (L, Tok);
         Count := Count + 1;
         Temp_Arr (Count) := Tok;
         exit when Tok.Kind = Tk_End_Of_Input;
      end loop;
      return Temp_Arr (1 .. Count);
   end Tokenize_Eager;

   -----------------------------------------------------------------------------
   -- Helpers
   -----------------------------------------------------------------------------
   function Is_Keyword (Text : String) return Boolean is
   begin
      if Text = "if" or else Text = "else" or else Text = "while" or else
         Text = "return" or else Text = "function" or else Text = "procedure" or else
         Text = "end" or else Text = "for" or else Text = "then" or else 
         Text = "loop"
      then
         return True;
      else
         return False;
      end if;
   end Is_Keyword;

   function To_String (Tok : Token) return String is
   begin
      return Tok.Kind'Image & " ('" & To_String (Tok.Text) & "') at " &
             Trim_Space (Tok.Line'Image) & ":" & Trim_Space (Tok.Column'Image);
   end To_String;

end Lexical_Analysis;
