--  Version: 0.001
--  Test suite for the Modular_Arithmetic library.  Every check is tagged
--  with the requirement it covers (REQ-xxx, see README.md).  Reference
--  values come from independent brute-force computations (small moduli,
--  exhaustive), from Interfaces.Unsigned_128 arithmetic (large moduli), or
--  from published check-digit examples that are valid by the algorithm
--  itself; invalid inputs are generated by mutating those examples.

pragma Ada_2022;

with Ada.Command_Line;
with Ada.Text_IO;
with Interfaces;
with Modular_Arithmetic;              use Modular_Arithmetic;
with Modular_Arithmetic.CRT;          use Modular_Arithmetic.CRT;
with Modular_Arithmetic.Montgomery;   use Modular_Arithmetic.Montgomery;
with Modular_Arithmetic.Check_Digits; use Modular_Arithmetic.Check_Digits;
with Modular_Arithmetic.Ring;
with Modular_Arithmetic.Big_Ring;

procedure Tests
  with SPARK_Mode => Off
is
   use type Interfaces.Unsigned_128;
   subtype U128 is Interfaces.Unsigned_128;

   Pass_Count : Natural := 0;
   Fail_Count : Natural := 0;

   procedure Check (Condition : Boolean; Message : String) is
   begin
      if Condition then
         Pass_Count := Pass_Count + 1;
         Ada.Text_IO.Put_Line ("  PASS: " & Message);
      else
         Fail_Count := Fail_Count + 1;
         Ada.Text_IO.Put_Line ("  FAIL: " & Message);
      end if;
   end Check;

   procedure Section (Title : String) is
   begin
      Ada.Text_IO.New_Line;
      Ada.Text_IO.Put_Line ("=== " & Title & " ===");
   end Section;

   function Img (X : Long_Long_Integer) return String is
      S : constant String := Long_Long_Integer'Image (X);
   begin
      return S (S'First + 1 .. S'Last);
   end Img;

   ---------------------------------------------------------------
   --  Independent references
   ---------------------------------------------------------------

   function Ref_Mul (A, B, N : Natural_64) return Natural_64 is
     (Natural_64 ((U128 (A) * U128 (B)) mod U128 (N)));

   function Ref_Add (A, B, N : Natural_64) return Natural_64 is
     (Natural_64 ((U128 (A) + U128 (B)) mod U128 (N)));

   function Ref_Pow (B, E, N : Natural_64) return Natural_64 is
      R : Natural_64 := 1 mod N;
   begin
      for I in 1 .. E loop
         R := Ref_Mul (R, B, N);
      end loop;
      return R;
   end Ref_Pow;

   function Ref_Gcd (A, B : Natural_64) return Natural_64 is
      X : Natural_64 := A;
      Y : Natural_64 := B;
      T : Natural_64;
   begin
      while Y /= 0 loop
         T := X mod Y;
         X := Y;
         Y := T;
      end loop;
      return X;
   end Ref_Gcd;

   --  Deterministic pseudo-random 63-bit values (splitmix-style mixing on
   --  unsigned 64-bit words).
   State : Interfaces.Unsigned_64 := 16#9E37_79B9_7F4A_7C15#;
   function Next return Natural_64 is
      use type Interfaces.Unsigned_64;
      Z : Interfaces.Unsigned_64;
   begin
      State := State + 16#9E37_79B9_7F4A_7C15#;
      Z := State;
      Z := (Z xor Interfaces.Shift_Right (Z, 30)) * 16#BF58_476D_1CE4_E5B9#;
      Z := (Z xor Interfaces.Shift_Right (Z, 27)) * 16#94D0_49BB_1331_11EB#;
      Z := Z xor Interfaces.Shift_Right (Z, 31);
      return Natural_64 (Interfaces.Shift_Right (Z, 1));
   end Next;

   P63 : constant Natural_64 := 2**63 - 25;   --  largest prime < 2**63
   M61 : constant Natural_64 := 2**61 - 1;    --  Mersenne prime
   P62 : constant Natural_64 := 2**62 - 57;   --  prime < 2**62 (odd)

   Big_Moduli : constant array (Positive range <>) of Natural_64 :=
     [P63, Max_Modulus, Max_Modulus - 1, M61, P62, 2**62, 2**32 + 15,
      1_000_000_007, 2**40];

   package Z97 is new Modular_Arithmetic.Ring (97);
   package Z12 is new Modular_Arithmetic.Ring (12);

begin
   Ada.Text_IO.Put_Line ("Modular_Arithmetic (SPARK) tests");
   Ada.Text_IO.Put_Line ("================================");

   ------------------------------------------------------------------
   Section ("1. Ring operations, exhaustive for N in 2 .. 40");
   ------------------------------------------------------------------
   declare
      Ok_Red, Ok_Add, Ok_Sub, Ok_Neg, Ok_Mul : Boolean := True;
   begin
      for N in Natural_64 range 2 .. 40 loop
         for A in 0 .. N - 1 loop
            if Neg_Mod (A, N) /= (N - A) mod N then
               Ok_Neg := False;
            end if;
            for B in 0 .. N - 1 loop
               if Add_Mod (A, B, N) /= (A + B) mod N then
                  Ok_Add := False;
               end if;
               if Sub_Mod (A, B, N) /= (A - B) mod N then
                  Ok_Sub := False;
               end if;
               if Mul_Mod (A, B, N) /= (A * B) mod N then
                  Ok_Mul := False;
               end if;
            end loop;
         end loop;
         for A in 0 .. 3 * N loop
            if Reduce (A, N) /= A mod N then
               Ok_Red := False;
            end if;
         end loop;
      end loop;
      Check (Ok_Red, "REQ-001 Reduce = A mod N (all A <= 3N, N <= 40)");
      Check (Ok_Add, "REQ-002 Add_Mod = (A+B) mod N (exhaustive)");
      Check (Ok_Sub, "REQ-003 Sub_Mod = (A-B) mod N (exhaustive)");
      Check (Ok_Neg, "REQ-004 Neg_Mod = (-A) mod N (exhaustive)");
      Check (Ok_Mul, "REQ-005 Mul_Mod = (A*B) mod N (exhaustive)");
   end;

   ------------------------------------------------------------------
   Section ("2. Ring operations near 2**63 (no overflow)");
   ------------------------------------------------------------------
   for N of Big_Moduli loop
      declare
         Ok_Add, Ok_Sub, Ok_Neg, Ok_Mul : Boolean := True;
         A, B : Natural_64;
      begin
         for I in 1 .. 2_000 loop
            case I is
               when 1 => A := N - 1; B := N - 1;
               when 2 => A := N - 1; B := 1;
               when 3 => A := 0;     B := N - 1;
               when 4 => A := N / 2; B := N / 2 + 1;
               when others => A := Next mod N; B := Next mod N;
            end case;
            if Add_Mod (A, B, N) /= Ref_Add (A, B, N) then
               Ok_Add := False;
            end if;
            if Sub_Mod (A, B, N) /= Ref_Add (A, N - B, N) then
               Ok_Sub := False;
            end if;
            if Neg_Mod (A, N) /= (N - A) mod N then
               Ok_Neg := False;
            end if;
            if Mul_Mod (A, B, N) /= Ref_Mul (A, B, N) then
               Ok_Mul := False;
            end if;
         end loop;
         Check (Ok_Add, "REQ-002 Add_Mod vs 128-bit reference, N=" & Img (N));
         Check (Ok_Sub, "REQ-003 Sub_Mod vs 128-bit reference, N=" & Img (N));
         Check (Ok_Neg, "REQ-004 Neg_Mod edge values, N=" & Img (N));
         Check (Ok_Mul, "REQ-005 Mul_Mod vs 128-bit reference, N=" & Img (N));
      end;
   end loop;
   Check (Mul_Mod (Max_Modulus - 1, Max_Modulus - 1, Max_Modulus) = 1,
          "REQ-005 (-1)*(-1) = 1 mod 2**63-1");
   Check (Add_Mod (Max_Modulus - 1, Max_Modulus - 1, Max_Modulus)
          = Max_Modulus - 2, "REQ-002 (-1)+(-1) = -2 mod 2**63-1");

   ------------------------------------------------------------------
   Section ("3. Pow_Mod");
   ------------------------------------------------------------------
   declare
      Ok : Boolean := True;
   begin
      for N in Natural_64 range 2 .. 30 loop
         for B in 0 .. N - 1 loop
            for E in Natural_64 range 0 .. 40 loop
               if Pow_Mod (B, E, N) /= Ref_Pow (B, E, N) then
                  Ok := False;
               end if;
            end loop;
         end loop;
      end loop;
      Check (Ok, "REQ-006 Pow_Mod = repeated multiplication (N<=30, E<=40)");
   end;
   Check (Pow_Mod (2, 10, 1000) = 24, "REQ-006 2**10 mod 1000 = 24");
   Check (Pow_Mod (0, 0, 7) = 1, "REQ-006 0**0 = 1");
   Check (Pow_Mod (4, 13, 497) = 445, "REQ-006 4**13 mod 497 = 445");
   declare
      Ok : Boolean := True;
      A  : Natural_64;
   begin
      for I in 1 .. 200 loop
         A := 1 + Next mod (P63 - 1);
         if Pow_Mod (A, P63 - 1, P63) /= 1 then
            Ok := False;
         end if;
         A := 1 + Next mod (M61 - 1);
         if Pow_Mod (A, M61 - 1, M61) /= 1 then
            Ok := False;
         end if;
      end loop;
      Check (Ok, "REQ-006 Fermat a**(p-1) = 1 for p = 2**63-25, 2**61-1");
      Check (Pow_Mod (2, 61, M61) = 1, "REQ-006 2**61 = 1 mod 2**61-1");
      Check (Pow_Mod (3, 1_000_000, 1_000_000_007)
             = Pow_Mod (Pow_Mod (3, 1_000, 1_000_000_007), 1_000,
                        1_000_000_007),
             "REQ-006 3**(10**6) = (3**1000)**1000");
      Check (Pow_Mod (P63 - 1, Max_Modulus, P63) = P63 - 1,
             "REQ-006 (-1)**odd = -1 near 2**63");
   end;

   ------------------------------------------------------------------
   Section ("4. Gcd, Bezout, Is_Unit, Inverse");
   ------------------------------------------------------------------
   declare
      Ok_G, Ok_B, Ok_U, Ok_I : Boolean := True;
      E : Bezout;
   begin
      for A in Natural_64 range 0 .. 70 loop
         for B in Natural_64 range 0 .. 70 loop
            E := Extended_Gcd (A, B);
            if E.G /= Ref_Gcd (A, B) or else Gcd (A, B) /= E.G then
               Ok_G := False;
            end if;
            if Wide (A) * E.X + Wide (B) * E.Y /= Wide (E.G) then
               Ok_B := False;
            end if;
         end loop;
      end loop;
      for N in Natural_64 range 2 .. 70 loop
         for A in 0 .. N - 1 loop
            if Is_Unit (A, N) /= (Ref_Gcd (A, N) = 1) then
               Ok_U := False;
            end if;
            if Is_Unit (A, N)
              and then (A * Inverse (A, N)) mod N /= 1 mod N
            then
               Ok_I := False;
            end if;
         end loop;
      end loop;
      Check (Ok_G, "REQ-008 Gcd = Euclid reference (A, B <= 70)");
      Check (Ok_B, "REQ-007 Bezout A*X + B*Y = G (A, B <= 70)");
      Check (Ok_U, "REQ-009 Is_Unit iff gcd = 1 (N <= 70)");
      Check (Ok_I, "REQ-010 A * Inverse(A) = 1 mod N (N <= 70)");
   end;
   Check (Gcd (0, 0) = 0, "REQ-008 gcd(0,0) = 0");
   Check (Gcd (0, 12) = 12 and then Gcd (12, 0) = 12, "REQ-008 gcd(0,12)");
   Check (Gcd (240, 46) = 2, "REQ-008 gcd(240,46) = 2");
   Check (Gcd (2**62, 3 * 2**40) = 2**40, "REQ-008 gcd(2**62, 3*2**40)");
   declare
      --  Consecutive Fibonacci numbers: the slowest case for Euclid.
      F91 : constant Natural_64 := 4_660_046_610_375_530_309;
      F92 : constant Natural_64 := 7_540_113_804_746_346_429;
      E   : constant Bezout := Extended_Gcd (F92, F91);
   begin
      Check (E.G = 1, "REQ-008 gcd(F92, F91) = 1");
      Check (Wide (F92) * E.X + Wide (F91) * E.Y = 1,
             "REQ-007 Bezout for F92, F91");
      Check (abs E.X <= Wide (F91) and then abs E.Y <= Wide (F92),
             "REQ-007 Bezout coefficients bounded");
   end;
   declare
      Ok : Boolean := True;
      A, I : Natural_64;
   begin
      for K in 1 .. 1_000 loop
         A := 1 + Next mod (P63 - 1);
         I := Inverse (A, P63);
         if Ref_Mul (A, I, P63) /= 1 or else I >= P63 then
            Ok := False;
         end if;
      end loop;
      Check (Ok, "REQ-010 Inverse mod 2**63-25 (1000 random units)");
      Check (Inverse (3, 7) = 5, "REQ-010 3**-1 mod 7 = 5");
      Check (Inverse (Max_Modulus - 1, Max_Modulus) = Max_Modulus - 1,
             "REQ-010 (-1)**-1 = -1 mod 2**63-1");
      Check (not Is_Unit (0, 5) and then not Is_Unit (6, 9)
             and then Is_Unit (1, 2),
             "REQ-009 non-units 0 mod 5, 6 mod 9; 1 mod 2 is a unit");
   end;

   ------------------------------------------------------------------
   Section ("5. Orbit_Length, Multiplicative_Order");
   ------------------------------------------------------------------
   declare
      Ok_O, Ok_M : Boolean := True;
      Seen : array (Natural_64 range 0 .. 60) of Boolean;
      Count, K : Natural_64;
      X : Natural_64;
   begin
      for N in Natural_64 range 2 .. 60 loop
         for A in 0 .. N - 1 loop
            --  distinct values of 0, A, 2A, ... mod N
            Seen := [others => False];
            Count := 0;
            X := 0;
            while not Seen (X) loop
               Seen (X) := True;
               Count := Count + 1;
               X := (X + A) mod N;
            end loop;
            if Orbit_Length (A, N) /= Count then
               Ok_O := False;
            end if;
            --  smallest K >= 1 with A**K = 1 (0 if none)
            K := 0;
            X := 1;
            for J in 1 .. N loop
               X := (X * A) mod N;
               if X = 1 then
                  K := J;
                  exit;
               end if;
            end loop;
            if Multiplicative_Order (A, N) /= K then
               Ok_M := False;
            end if;
         end loop;
      end loop;
      Check (Ok_O, "REQ-011 Orbit_Length = count of distinct multiples");
      Check (Ok_M, "REQ-012 Multiplicative_Order = brute force (N <= 60)");
   end;
   Check (Orbit_Length (4, 10) = 5, "REQ-011 multiples of 4 mod 10: 5");
   Check (Orbit_Length (0, 10) = 1, "REQ-011 multiples of 0: 1");
   Check (Orbit_Length (3, P63) = P63, "REQ-011 orbit of a unit is N");
   Check (Multiplicative_Order (2, 7) = 3, "REQ-012 ord_7(2) = 3");
   Check (Multiplicative_Order (3, 7) = 6, "REQ-012 ord_7(3) = 6 (primitive)");
   Check (Multiplicative_Order (10, 97) = 96, "REQ-012 ord_97(10) = 96");
   Check (Multiplicative_Order (2, 8) = 0, "REQ-012 2 mod 8 has no order");
   Check (Multiplicative_Order (1, Max_Modulus) = 1
          and then Multiplicative_Order (Max_Modulus - 1, Max_Modulus) = 2,
          "REQ-012 orders 1 and 2 at the largest modulus 2**63-1");

   ------------------------------------------------------------------
   Section ("6. Chinese Remainder Theorem");
   ------------------------------------------------------------------
   Check (Crt2 (2, 3, 3, 5) = 8, "REQ-013 x=2 (3), x=3 (5) -> 8");
   Check (Crt_Array ([(2, 3), (3, 5), (2, 7)]) = 23,
          "REQ-014 Sunzi: x=2 (3), 3 (5), 2 (7) -> 23");
   Check (Crt_Array ([(1, 2)]) = 1, "REQ-014 single congruence");
   declare
      Ok_Map, Ok_Uni : Boolean := True;
      X : Natural_64;
   begin
      for M1 in Natural_64 range 2 .. 25 loop
         for M2 in Natural_64 range 2 .. 25 loop
            if Ref_Gcd (M1, M2) = 1 then
               for V in 0 .. M1 * M2 - 1 loop
                  --  Crt2 inverts V -> (V mod M1, V mod M2): the map is a
                  --  bijection, so the solution below M1*M2 is unique.
                  X := Crt2 (V mod M1, M1, V mod M2, M2);
                  if X /= V then
                     Ok_Uni := False;
                  end if;
                  if X mod M1 /= V mod M1 or else X mod M2 /= V mod M2 then
                     Ok_Map := False;
                  end if;
               end loop;
            end if;
         end loop;
      end loop;
      Check (Ok_Map, "REQ-013 Crt2 residues correct (all coprime M1,M2<=25)");
      Check (Ok_Uni, "REQ-015 Crt2 (V mod M1, V mod M2) = V (uniqueness)");
   end;
   declare
      M1 : constant Natural_64 := 2**31 - 1;          --  prime
      M2 : constant Natural_64 := 2**31 + 11;         --  odd, coprime
      Ok : Boolean := True;
      R1, R2, X : Natural_64;
   begin
      Check (Gcd (M1, M2) = 1, "REQ-013 test moduli 2**31-1, 2**31+11 coprime");
      for I in 1 .. 500 loop
         R1 := Next mod M1;
         R2 := Next mod M2;
         X := Crt2 (R1, M1, R2, M2);
         if X mod M1 /= R1 or else X mod M2 /= R2
           or else Wide (X) >= Wide (M1) * Wide (M2)
         then
            Ok := False;
         end if;
      end loop;
      Check (Ok, "REQ-013 Crt2 with product near 2**62 (500 cases)");
   end;
   declare
      C : constant Congruence_Array :=
        [(1, 4), (2, 9), (3, 5), (6, 7), (10, 11), (12, 13), (0, 17),
         (18, 19), (22, 23)];
      X : constant Natural_64 := Crt_Array (C);
      Ok : Boolean := True;
   begin
      for E of C loop
         if X mod E.M /= E.R then
            Ok := False;
         end if;
      end loop;
      Check (Ok and then Wide (X) < Prefix_Product (C, C'Last),
             "REQ-014 nine moduli (product 2*2*9*5*7*...*23)");
   end;

   ------------------------------------------------------------------
   Section ("7. Montgomery multiplication");
   ------------------------------------------------------------------
   declare
      Moduli : constant array (Positive range <>) of Natural_64 :=
        [3, 5, 97, 101, 1_000_000_007, M61, P62, R - 1, R - 3];
      Ok_C, Ok_M, Ok_T, Ok_R : Boolean := True;
      Ctx : Context;
      A, B : Natural_64;
   begin
      for N of Moduli loop
         Ctx := Make_Context (N);
         if not Valid (Ctx) then
            Ok_C := False;
         end if;
         for I in 1 .. 1_000 loop
            case I is
               when 1 => A := N - 1; B := N - 1;
               when 2 => A := 0;     B := N - 1;
               when 3 => A := 1;     B := 1;
               when others => A := Next mod N; B := Next mod N;
            end case;
            if Multiply (A, B, Ctx) /= Ref_Mul (A, B, N) then
               Ok_M := False;
            end if;
            if From_Montgomery (To_Montgomery (A, Ctx), Ctx) /= A then
               Ok_T := False;
            end if;
            if Ref_Mul (Redc (Wide (A) * Wide (B), Ctx), Natural_64 (R mod N), N)
              /= Ref_Mul (A, B, N)
            then
               Ok_R := False;
            end if;
         end loop;
      end loop;
      Check (Ok_C, "REQ-016 Make_Context valid for 9 odd moduli up to 2**62-1");
      Check (Ok_M, "REQ-018 Montgomery Multiply = A*B mod N (9000 cases)");
      Check (Ok_T, "REQ-018 From (To (A)) = A");
      Check (Ok_R, "REQ-017 Redc (T) * R = T (mod N)");
   end;
   declare
      Ctx : constant Context := Make_Context (97);
   begin
      Check (Ctx.R_Mod_N = R mod 97, "REQ-016 R mod 97");
      Check ((Ctx.R_Mod_N * Ctx.R_Inv) mod 97 = 1, "REQ-016 R * R^-1 = 1 mod 97");
      Check (Ref_Mul (97, Ctx.N_Prime, R) = R - 1, "REQ-016 N * N' = -1 mod R");
      Check (To_Montgomery (1, Ctx) = R mod 97, "REQ-017 To (1) = R mod N");
      Check (Montgomery_Multiply (To_Montgomery (5, Ctx), To_Montgomery (7, Ctx), Ctx)
             = To_Montgomery (35, Ctx), "REQ-017 Mont (5R, 7R) = 35R");
   end;

   ------------------------------------------------------------------
   Section ("8. Generic Ring instances");
   ------------------------------------------------------------------
   Check (Z97.Add (96, 5) = 4 and then Z97.Sub (3, 5) = 95
          and then Z97.Neg (1) = 96 and then Z97.Mul (50, 2) = 3,
          "REQ-023 Z/97: add, sub, neg, mul");
   Check (Z97.Reduce (1234) = 1234 mod 97, "REQ-023 Z/97 reduce");
   Check (Z97.Pow (10, 96) = 1 and then Z97.Order (10) = 96,
          "REQ-023 Z/97: 10**96 = 1, order 96");
   Check (Z97.Is_Unit (5) and then Z97.Mul (5, Z97.Inverse (5)) = 1,
          "REQ-023 Z/97 inverse of 5");
   Check (Z12.Orbit_Length (8) = 3 and then not Z12.Is_Unit (8)
          and then Z12.Order (8) = 0, "REQ-023 Z/12: orbit of 8 = 3, not a unit");
   Check (Big_Ring.Mul (Big_Ring.N - 1, 2) = Big_Ring.N - 2,
          "REQ-023 Z/(2**63-25): (-1)*2 = -2");
   Check (Big_Ring.Mul (123_456_789, Big_Ring.Inverse (123_456_789)) = 1,
          "REQ-023 Z/(2**63-25) inverse");

   ------------------------------------------------------------------
   Section ("9. Check digits: published valid examples");
   ------------------------------------------------------------------
   declare
      type Str is access constant String;
      Ibans : constant array (Positive range <>) of Str :=
        [new String'("DE89 3704 0044 0532 0130 00"),
         new String'("GB82 WEST 1234 5698 7654 32"),
         new String'("GB29 NWBK 6016 1331 9268 19"),
         new String'("FR14 2004 1010 0505 0001 3M02 606"),
         new String'("NL91 ABNA 0417 1643 00"),
         new String'("BE68 5390 0754 7034"),
         new String'("CH93 0076 2011 6238 5295 7"),
         new String'("NO93 8601 1117 947"),
         new String'("AT61 1904 3002 3457 3201"),
         new String'("IT60 X054 2811 1010 0000 0123 456")];
      Isbn10s : constant array (Positive range <>) of Str :=
        [new String'("0-306-40615-2"), new String'("99921-58-10-7"),
         new String'("0-8044-2957-X"), new String'("3-16-148410-X"),
         new String'("0-19-853453-1"), new String'("1-84356-028-3")];
      Ean13s : constant array (Positive range <>) of Str :=
        [new String'("978-0-306-40615-7"), new String'("978-3-16-148410-0"),
         new String'("4006381333931"), new String'("978-1-86197-876-9"),
         new String'("5901234123457"), new String'("9780262033848")];
      Luhns : constant array (Positive range <>) of Str :=
        [new String'("79927398713"), new String'("4111 1111 1111 1111"),
         new String'("4012 8888 8888 1881"), new String'("3782 822463 10005"),
         new String'("5555 5555 5555 4444"), new String'("6011 1111 1111 1117")];

      --  Digits of S (separators removed).
      function Digits_Of (S : String) return String is
         R : String (1 .. S'Length);
         L : Natural := 0;
      begin
         for C of S loop
            if C /= ' ' and then C /= '-' then
               L := L + 1;
               R (L) := C;
            end if;
         end loop;
         return R (1 .. L);
      end Digits_Of;

      type Validator is access function (S : String) return Boolean;

      --  Every single-digit substitution must be rejected.
      function All_Substitutions_Rejected
        (S : String; V : Validator; From : Positive) return Boolean
      is
         D : constant String := Digits_Of (S);
         M : String := D;
      begin
         for I in From .. D'Last loop
            if Is_Digit (D (I)) then
               for C in Character range '0' .. '9' loop
                  if C /= D (I) then
                     M := D;
                     M (I) := C;
                     if V (M) then
                        return False;
                     end if;
                  end if;
               end loop;
            end if;
         end loop;
         return True;
      end All_Substitutions_Rejected;

      --  Adjacent transpositions of different digits: return the number
      --  of undetected swaps and whether they are all in the "allowed"
      --  set (Allowed (a, b) = the scheme cannot detect a <-> b).
      type Pair_Rule is access function (A, B : Character) return Boolean;

      function Transpositions_Ok
        (S : String; V : Validator; Allowed : Pair_Rule; From : Positive)
         return Boolean
      is
         D : constant String := Digits_Of (S);
         M : String := D;
      begin
         for I in From .. D'Last - 1 loop
            if Is_Digit (D (I)) and then Is_Digit (D (I + 1))
              and then D (I) /= D (I + 1)
            then
               M := D;
               M (I) := D (I + 1);
               M (I + 1) := D (I);
               if V (M) /= Allowed (D (I), D (I + 1)) then
                  return False;
               end if;
            end if;
         end loop;
         return True;
      end Transpositions_Ok;

      function Never (A, B : Character) return Boolean is (False and then A = B);
      function Ean_Blind (A, B : Character) return Boolean is
        (abs (Character'Pos (A) - Character'Pos (B)) = 5);
      function Luhn_Blind (A, B : Character) return Boolean is
        ((A = '0' and then B = '9') or else (A = '9' and then B = '0'));

      Ok_V, Ok_S, Ok_T : Boolean;
   begin
      --  IBAN (REQ-019)
      Ok_V := True; Ok_S := True; Ok_T := True;
      for S of Ibans loop
         Ok_V := Ok_V and then Iban_Valid (S.all);
         Ok_S := Ok_S and then All_Substitutions_Rejected
                                 (S.all, Iban_Valid'Access, 3);
         Ok_T := Ok_T and then Transpositions_Ok
                                 (S.all, Iban_Valid'Access, Never'Access, 3);
      end loop;
      Check (Ok_V, "REQ-019 IBAN: 10 published examples valid");
      Check (Ok_S, "REQ-019 IBAN: every single-digit change rejected");
      Check (Ok_T, "REQ-019 IBAN: every adjacent digit swap rejected");
      Check (Iban_Check_Digits ("DE", "370400440532013000") = "89",
             "REQ-019 IBAN check digits DE..370400440532013000 = 89");
      Check (Iban_Check_Digits ("GB", "WEST12345698765432") = "82",
             "REQ-019 IBAN check digits GB..WEST12345698765432 = 82");
      Check (Iban_Valid ("de89370400440532013000"),
             "REQ-019 IBAN: lower case and no spaces accepted");
      Check (not Iban_Valid ("DE88 3704 0044 0532 0130 00"),
             "REQ-019 IBAN: wrong check digits rejected");
      Check (not Iban_Valid ("DE89 3704 0044 0532 0130 0"),
             "REQ-019 IBAN: deleted digit rejected");
      Check (not Iban_Valid ("") and then not Iban_Valid ("DE89")
             and then not Iban_Valid ("1E89 3704 0044 0532 0130 00")
             and then not Iban_Valid ("DE8X 3704 0044 0532 0130 00")
             and then not Iban_Valid ("DE89 3704 0044 0532 0130 00!")
             and then not Iban_Valid ("DE89 3704 0044 0532 0130 0012 3456 7890 12"),
             "REQ-019 IBAN: malformed inputs rejected");

      --  ISBN-10 (REQ-020)
      Ok_V := True; Ok_S := True; Ok_T := True;
      for S of Isbn10s loop
         Ok_V := Ok_V and then Isbn10_Valid (S.all);
         Ok_S := Ok_S and then All_Substitutions_Rejected
                                 (S.all, Isbn10_Valid'Access, 1);
         Ok_T := Ok_T and then Transpositions_Ok
                                 (S.all, Isbn10_Valid'Access, Never'Access, 1);
      end loop;
      Check (Ok_V, "REQ-020 ISBN-10: 6 published examples valid");
      Check (Ok_S, "REQ-020 ISBN-10: every single-digit change rejected");
      Check (Ok_T, "REQ-020 ISBN-10: every adjacent digit swap rejected");
      Check (Isbn10_Check_Digit ("030640615") = '2'
             and then Isbn10_Check_Digit ("080442957") = 'X',
             "REQ-020 ISBN-10 check digit 2 and X");
      Check (Isbn10_Valid ("0-8044-2957-x"), "REQ-020 ISBN-10 lower-case x");
      Check (not Isbn10_Valid ("0-8044-X957-2")
             and then not Isbn10_Valid ("0-306-40615")
             and then not Isbn10_Valid ("0-306-40615-22"),
             "REQ-020 ISBN-10: X inside, too short, too long rejected");

      --  EAN-13 / ISBN-13 (REQ-021)
      Ok_V := True; Ok_S := True; Ok_T := True;
      for S of Ean13s loop
         Ok_V := Ok_V and then Ean13_Valid (S.all);
         Ok_S := Ok_S and then All_Substitutions_Rejected
                                 (S.all, Ean13_Valid'Access, 1);
         Ok_T := Ok_T and then Transpositions_Ok
                                 (S.all, Ean13_Valid'Access,
                                  Ean_Blind'Access, 1);
      end loop;
      Check (Ok_V, "REQ-021 EAN-13: 6 published examples valid");
      Check (Ok_S, "REQ-021 EAN-13: every single-digit change rejected");
      Check (Ok_T, "REQ-021 EAN-13: swaps rejected iff digits differ by /= 5");
      Check (Isbn13_Valid ("978-0-306-40615-7")
             and then not Isbn13_Valid ("4006381333931"),
             "REQ-021 ISBN-13 needs prefix 978/979");
      Check (Ean13_Check_Digit ("978030640615") = '7'
             and then Ean13_Check_Digit ("400638133393") = '1',
             "REQ-021 EAN-13 check digits");
      Check (not Ean13_Valid ("978-0-306-40615") and then not Ean13_Valid ("97803064061X7"),
             "REQ-021 EAN-13: too short / non-digit rejected");

      --  Luhn (REQ-022)
      Ok_V := True; Ok_S := True; Ok_T := True;
      for S of Luhns loop
         Ok_V := Ok_V and then Luhn_Valid (S.all);
         Ok_S := Ok_S and then All_Substitutions_Rejected
                                 (S.all, Luhn_Valid'Access, 1);
         Ok_T := Ok_T and then Transpositions_Ok
                                 (S.all, Luhn_Valid'Access,
                                  Luhn_Blind'Access, 1);
      end loop;
      Check (Ok_V, "REQ-022 Luhn: 6 published examples valid");
      Check (Ok_S, "REQ-022 Luhn: every single-digit change rejected");
      Check (Ok_T, "REQ-022 Luhn: swaps rejected except 09 <-> 90");
      Check (Luhn_Check_Digit ("7992739871") = '3',
             "REQ-022 Luhn check digit of 7992739871 = 3");
      Check (not Luhn_Valid ("0") and then not Luhn_Valid ("79927398713a")
             and then Luhn_Valid ("00"),
             "REQ-022 Luhn: too short / non-digit rejected, 00 valid");
      declare
         Ok : Boolean := True;
      begin
         for S of Luhns loop
            declare
               D : constant String := Digits_Of (S.all);
            begin
               Ok := Ok and then Luhn_Check_Digit (D (D'First .. D'Last - 1))
                                 = D (D'Last);
            end;
         end loop;
         for S of Ean13s loop
            declare
               D : constant String := Digits_Of (S.all);
            begin
               Ok := Ok and then Ean13_Check_Digit (D (D'First .. D'Last - 1))
                                 = D (D'Last);
            end;
         end loop;
         Check (Ok, "REQ-021/022 check-digit generators reproduce examples");
      end;

      --  Strings whose index range ends at Integer'Last (e.g. slices of a
      --  large buffer): the generators must not compute out-of-range indices.
      declare
         Hi10 : constant String (Integer'Last - 8 .. Integer'Last) :=
           "030640615";
         Hi12 : constant String (Integer'Last - 11 .. Integer'Last) :=
           "978030640615";
         Hi3  : constant String (Integer'Last - 9 .. Integer'Last) :=
           "7992739871";
      begin
         Check (Isbn10_Check_Digit (Hi10) = '2'
                and then Ean13_Check_Digit (Hi12) = '7'
                and then Luhn_Check_Digit (Hi3) = '3',
                "REQ-020/021/022 check digits of strings indexed up to "
                & "Integer'Last");
      end;
   end;

   ------------------------------------------------------------------
   Section ("10. Check digits: boundary inputs with valid checksums");
   ------------------------------------------------------------------
   declare
      --  Test-side reference: IBAN remainder of the rearranged string
      --  (plain Integer arithmetic, independent of the library).
      function Ref_Iban_Rem (S : String) return Integer is
         T : constant String :=
           S (S'First + 4 .. S'Last) & S (S'First .. S'First + 3);
         R : Integer := 0;
      begin
         for C of T loop
            if C in '0' .. '9' then
               R := (R * 10 + (Character'Pos (C) - 48)) mod 97;
            else
               R := (R * 100 + (Character'Pos (C) - 55)) mod 97;
            end if;
         end loop;
         return R;
      end Ref_Iban_Rem;

      --  S with the two characters at positions P, P+1 replaced by the
      --  first digit pair that makes the reference remainder 1.
      function Fix (S : String; P : Positive := 3) return String is
         M : String := S;
      begin
         for A in Character range '0' .. '9' loop
            for B in Character range '0' .. '9' loop
               M (M'First + P - 1) := A;
               M (M'First + P) := B;
               if Ref_Iban_Rem (M) = 1 then
                  return M;
               end if;
            end loop;
         end loop;
         return S;
      end Fix;

      Thirty : constant String := "123456789012345678901234567890";
      I34 : constant String := Fix ("DE00" & Thirty);
      I35 : constant String := Fix ("DE00" & Thirty & "1");
      I5  : constant String := Fix ("AA001");
      I1D : constant String := Fix ("1E00" & Thirty (1 .. 18));
      I3L : constant String := Fix ("DEA0" & Thirty (1 .. 18), 21);
      I4L : constant String := Fix ("DE0A" & Thirty (1 .. 18), 21);

      --  ISBN-10 with an 'X' inside and a matching final symbol.
      function Isbn10_X_Inside return String is
         Base : constant String := "0306X0615";
         Sum  : Integer := 0;
      begin
         for I in Base'Range loop
            Sum := Sum + (11 - I)
              * (if Base (I) = 'X' then 10 else Character'Pos (Base (I)) - 48);
         end loop;
         Sum := (11 - Sum mod 11) mod 11;
         return Base & (if Sum = 10 then 'X' else Character'Val (48 + Sum));
      end Isbn10_X_Inside;

      --  EAN-13 check digit by the test-side reference.
      function Ref_Ean (S : String) return String is
         Sum : Integer := 0;
      begin
         for I in S'Range loop
            Sum := Sum + (if (I - S'First) mod 2 = 0 then 1 else 3)
              * (Character'Pos (S (I)) - 48);
         end loop;
         return S & Character'Val (48 + (10 - Sum mod 10) mod 10);
      end Ref_Ean;

      E979 : constant String := Ref_Ean ("979109063607");
      E977 : constant String := Ref_Ean ("977123456700");
   begin
      Check (Ref_Iban_Rem (I34) = 1 and then I34'Length = 34
             and then Iban_Valid (I34),
             "REQ-019 IBAN: 34 characters with valid checksum accepted");
      Check (Ref_Iban_Rem (I35) = 1 and then not Iban_Valid (I35),
             "REQ-019 IBAN: 35 characters rejected despite valid checksum");
      Check (Ref_Iban_Rem (I5) = 1 and then Iban_Valid (I5),
             "REQ-019 IBAN: 5 characters with valid checksum accepted");
      Check (Ref_Iban_Rem ("AA75") = 1 and then not Iban_Valid ("AA75"),
             "REQ-019 IBAN: 4 characters rejected despite valid checksum");
      Check (Ref_Iban_Rem (I1D) = 1 and then not Iban_Valid (I1D),
             "REQ-019 IBAN: digit in country code rejected (valid checksum)");
      Check (Ref_Iban_Rem (I3L) = 1 and then not Iban_Valid (I3L)
             and then Ref_Iban_Rem (I4L) = 1 and then not Iban_Valid (I4L),
             "REQ-019 IBAN: letter in check digits rejected (valid checksum)");
      Check (not Isbn10_Valid (Isbn10_X_Inside),
             "REQ-020 ISBN-10: X inside rejected even with matching sum");
      Check (Isbn10_Check_Digit ("999215810") = '7'
             and then Isbn10_Check_Digit ("316148410") = 'X'
             and then Isbn10_Check_Digit ("184356028") = '3',
             "REQ-020 ISBN-10 check digits with non-zero leading digit");
      Check (not Ean13_Valid ("40063813339310")
             and then not Ean13_Valid ("400638133393"),
             "REQ-021 EAN-13: 14 and 12 digits rejected");
      Check (Isbn13_Valid (E979) and then Ean13_Valid (E977)
             and then not Isbn13_Valid (E977),
             "REQ-021 ISBN-13: 979 accepted, 977 (not Bookland) rejected");
   end;

   Ada.Text_IO.New_Line;
   Ada.Text_IO.Put_Line
     ("Summary:" & Natural'Image (Pass_Count) & " passed,"
      & Natural'Image (Fail_Count) & " failed");
   if Fail_Count /= 0 then
      Ada.Command_Line.Set_Exit_Status (Ada.Command_Line.Failure);
   end if;
end Tests;
