--  Own checks (see tests/SOURCES.txt). Assume Hidden_Subgroup_Problem is
--  wrong or does nothing. Oracles are built with a KNOWN hidden subgroup, so
--  the expected answer is the construction parameter, not a recomputation:
--  * Z_N, N = 2 .. 40: f (x) = 7 * (x mod r) + 1 for every divisor r of N
--    (r = N included: one-to-one, H = {0}) hides H = r Z_N (period r); answers are checked by certificate
--    (Verify_Hidden_Subgroup) and by comparing the generated subgroup with H;
--  * Verify_Hidden_Subgroup: h is in H iff r divides h (every h, every r);
--  * characters: g annihilates h iff N / gcd (N, h) divides g;
--  * GCD: largest common divisor by downward search;
--  * Simon, n = 1 .. 5 bits, every s /= 0: f (x) = min (x, x xor s).
pragma Ada_2022;
with Ada.Text_IO; use Ada.Text_IO;
with Hidden_Subgroup_Problem; use Hidden_Subgroup_Problem;

procedure Own_Checks is
   Failures : Natural := 0;
   Checked  : Natural := 0;

   procedure Expect (Cond : Boolean; What : String) is
   begin
      Checked := Checked + 1;
      if not Cond then
         Failures := Failures + 1;
         if Failures <= 25 then
            Put_Line ("  FAIL own: " & What);
         end if;
      end if;
   end Expect;

   R_Hidden : Group_Element := 1;
   S_Hidden : Bit_Mask := 1;

   function Coset_Oracle (X : Group_Element) return Group_Element is
     (7 * (X mod R_Hidden) + 1);
   function Simon_Oracle (X : Bit_Mask) return Bit_Mask is
     (Bit_Mask'Min (X, X xor S_Hidden));

   function Ref_GCD (A, B : Group_Element) return Group_Element is
   begin
      if A = 0 then
         return B;
      elsif B = 0 then
         return A;
      end if;
      for D in reverse 1 .. Group_Element'Min (A, B) loop
         if A mod D = 0 and then B mod D = 0 then
            return D;
         end if;
      end loop;
      return 1;
   end Ref_GCD;

   --  subgroup of Z_N generated by Gens, as a membership table
   type Member_Table is array (Group_Element range 0 .. 64) of Boolean;
   function Generated (N : Group_Element; Gens : Element_Array) return Member_Table is
      T : Member_Table := [0 => True, others => False];
      Changed : Boolean := True;
   begin
      while Changed loop
         Changed := False;
         for X in 0 .. N - 1 loop
            if T (X) then
               for G of Gens loop
                  if not T ((X + G) mod N) then
                     T ((X + G) mod N) := True;
                     Changed := True;
                  end if;
               end loop;
            end if;
         end loop;
      end loop;
      return T;
   end Generated;
begin
   for N in Group_Element range 2 .. 40 loop
      for R in Group_Element range 1 .. N loop   --  R = N: one-to-one oracle, H = {0}
         if N mod R = 0 then
            R_Hidden := R;
            declare
               H_Ref : Member_Table := [others => False];
            begin
               for X in 0 .. N - 1 loop
                  H_Ref (X) := X mod R = 0;
               end loop;
               if R = 1 then
                  --  constant oracle: spec / tests expect an exception
                  begin
                     declare
                        P : constant Period_Type := Solve_Period_Finding (N, Coset_Oracle'Unrestricted_Access);
                     begin
                        Expect (False, "constant oracle accepted, period" & P'Image);
                     end;
                  exception
                     when Invalid_Oracle | Subgroup_Not_Found => Expect (True, "");
                  end;
               else
                  begin
                     Expect (Solve_Period_Finding (N, Coset_Oracle'Unrestricted_Access) = Period_Type (R),
                             "period N=" & N'Image & " r=" & R'Image);
                     declare
                        Gens : constant Element_Array := Solve_Abelian_HSP (N, Coset_Oracle'Unrestricted_Access);
                        T    : constant Member_Table := Generated (N, Gens);
                        Same : Boolean := True;
                     begin
                        for X in 0 .. N - 1 loop
                           Same := Same and then T (X) = H_Ref (X);
                        end loop;
                        Expect (Same, "Solve_Abelian_HSP generates H = r Z_N, N=" & N'Image & " r=" & R'Image
                                & " got" & Gens (Gens'First)'Image);
                        Expect (Verify_Hidden_Subgroup (N, Gens, Coset_Oracle'Unrestricted_Access),
                                "certificate: Verify_Hidden_Subgroup accepts the HSP answer, N=" & N'Image
                                & " r=" & R'Image);
                     end;
                  exception
                     when Subgroup_Not_Found | Invalid_Oracle =>
                        Expect (False, "period / HSP raised for N=" & N'Image & " r=" & R'Image);
                  end;
               end if;
               for Hh in 0 .. N - 1 loop
                  Expect (Verify_Hidden_Subgroup (N, [1 => Hh], Coset_Oracle'Unrestricted_Access) = H_Ref (Hh),
                          "Verify_Hidden_Subgroup N=" & N'Image & " r=" & R'Image & " h=" & Hh'Image);
                  Expect (Verify_Hidden_Subgroup (N, [R, Hh], Coset_Oracle'Unrestricted_Access) = H_Ref (Hh),
                          "Verify_Hidden_Subgroup pair N=" & N'Image & " h=" & Hh'Image);
               end loop;
            end;
         end if;
      end loop;
      for G in 0 .. N - 1 loop
         for Hh in 0 .. N - 1 loop
            Expect (Evaluate_Character_Orthogonality (N, G, [1 => Hh])
                      = (G mod (N / Ref_GCD (N, Hh)) = 0),
                    "character N=" & N'Image & " g=" & G'Image & " h=" & Hh'Image);
         end loop;
         Expect (Evaluate_Character_Orthogonality (N, G, [N / 2, 0, 1]) = (G mod N = 0),
                 "character on [N/2, 0, 1]");
      end loop;
   end loop;
   for A in Group_Element range 0 .. 60 loop
      for B in Group_Element range 0 .. 60 loop
         Expect (Greatest_Common_Divisor (A, B) = Ref_GCD (A, B), "gcd" & A'Image & B'Image);
      end loop;
   end loop;
   for Bits in 1 .. 5 loop
      for S in Bit_Mask range 1 .. Bit_Mask (2 ** Bits - 1) loop
         S_Hidden := S;
         Expect (Solve_Simons_Problem (Bits, Simon_Oracle'Unrestricted_Access) = S,
                 "Simon n=" & Bits'Image & " s=" & S'Image);
      end loop;
   end loop;
   --  s = 0 (one-to-one oracle): no non-zero s exists
   S_Hidden := 0;
   begin
      Expect (Solve_Simons_Problem (4, Simon_Oracle'Unrestricted_Access) = 0, "Simon s=0 returned a value");
   exception
      when Subgroup_Not_Found => Expect (True, "");
   end;
   if Failures > 0 then
      Put_Line ("FAIL own checks:" & Failures'Image & " of" & Checked'Image);
      raise Program_Error with "own checks failed";
   end if;
   Put_Line ("PASS own checks:" & Checked'Image & " (known hidden subgroups, certificates, gcd and character properties)");
end Own_Checks;
