pragma Ada_2022;
--  Own checks for Binomial_Coefficient.Choose (see tests/SOURCES.txt). No
--  expected value comes from the program: every (N, K) in 0 .. 33 is
--  compared with the multiplicative formula in Long_Long_Integer, and the
--  results must satisfy symmetry, Pascal's rule, row sums 2 ** N and
--  Vandermonde's identity. The ghost Pow2 table is regenerated by doubling.
with Ada.Text_IO;
with Binomial_Coefficient; use Binomial_Coefficient;

procedure Own_Checks with SPARK_Mode => Off is
   Failures : Natural := 0;
   Checked  : Natural := 0;

   procedure Report (Ok : Boolean; Label : String) is
   begin
      Checked := Checked + 1;
      if not Ok then
         Failures := Failures + 1;
         if Failures <= 10 then
            Ada.Text_IO.Put_Line ("  FAIL own check: " & Label);
         end if;
      end if;
   end Report;

   --  C (N, K) = prod_{i = 1 .. K} (N - K + i) / i; after step i the value
   --  is C (N - K + i, i), so every division is exact. The largest
   --  intermediate is C (33, 16) * 33 < 2 ** 63.
   function Formula (N, K : Natural) return Long_Long_Integer is
      C : Long_Long_Integer := 1;
   begin
      if K > N then
         return 0;
      end if;
      for I in 1 .. K loop
         C := C * Long_Long_Integer (N - K + I) / Long_Long_Integer (I);
      end loop;
      return C;
   end Formula;

   function Img (N, K : Natural) return String is
     ("(" & N'Image & "," & K'Image & ")");

   Power : Long_Long_Integer := 1;
   Sum   : Long_Long_Integer;
begin
   for N in Input loop
      --  Pow2 regenerated by doubling, entry by entry.
      if N > 0 then
         Power := 2 * Power;
      end if;
      pragma Assert (Long_Long_Integer (Pow2 (N)) = Power);

      Sum := 0;
      for K in Input loop
         Report (Long_Long_Integer (Choose (N, K)) = Formula (N, K), "formula" & Img (N, K));
         --  The ghost spec itself against the formula.
         pragma Assert (Long_Long_Integer (Pascal_Row (N) (K)) = Formula (N, K));
         if K <= N then
            Report (Choose (N, K) = Choose (N, N - K), "symmetry" & Img (N, K));
            Sum := Sum + Long_Long_Integer (Choose (N, K));
         else
            Report (Choose (N, K) = 0, "zero above N" & Img (N, K));
         end if;
         if N >= 1 and then K >= 1 then
            Report (Choose (N, K) = Choose (N - 1, K - 1) + Choose (N - 1, K),
                    "Pascal" & Img (N, K));
         end if;
      end loop;
      Report (Sum = Power, "row sum" & N'Image);
   end loop;

   --  Vandermonde: sum_j C (A, J) * C (B, K - J) = C (A + B, K).
   for A in 0 .. 15 loop
      for B in 0 .. 15 loop
         for K in 0 .. A + B loop
            Sum := 0;
            for J in 0 .. K loop
               Sum := Sum + Long_Long_Integer (Choose (A, J)) * Long_Long_Integer (Choose (B, K - J));
            end loop;
            Report (Sum = Long_Long_Integer (Choose (A + B, K)),
                    "Vandermonde" & Img (A, B) & K'Image);
         end loop;
      end loop;
   end loop;

   Ada.Text_IO.Put_Line ("own checks:" & Checked'Image & " checks," & Failures'Image & " failures");
   if Failures > 0 then
      raise Program_Error with "own checks failed";
   end if;
end Own_Checks;
