pragma Ada_2022;
--  Own checks for Combination_Sum (see tests/SOURCES.txt). No expected
--  value comes from the program. References, each built differently from
--  the code's "drop part C or use it once more" recurrence:
--  * by multiplicity: choose how many copies of the largest part to use;
--  * conjugation: parts <= C is counted as partitions into at most C parts;
--  * Euler's pentagonal-number recurrence for p (n);
--  * closed forms for parts <= 1, 2, 3.
--  The ghost Pow2 table is regenerated by doubling.
with Ada.Text_IO;
with Combination_Sum; use Combination_Sum;

procedure Own_Checks with SPARK_Mode => Off is
   Failures : Natural := 0;
   Checked  : Natural := 0;

   procedure Report (Ok : Boolean; Label : String) is
   begin
      Checked := Checked + 1;
      if not Ok then
         Failures := Failures + 1;
         if Failures <= 10 then
            Ada.Text_IO.Put_Line ("  FAIL own check: " & Label);
         end if;
      end if;
   end Report;

   subtype Count is Long_Long_Integer;

   --  Multisets of parts 1 .. C summing to N: take M copies of part C
   --  (M = 0 .. N / C) and fill the rest with parts 1 .. C - 1.
   function By_Multiplicity (N, C : Natural) return Count is
      Sum : Count := 0;
   begin
      if C = 0 then
         return (if N = 0 then 1 else 0);
      end if;
      for M in 0 .. N / C loop
         Sum := Sum + By_Multiplicity (N - M * C, C - 1);
      end loop;
      return Sum;
   end By_Multiplicity;

   --  Partitions of N into exactly K parts: either a part is 1 (remove it)
   --  or all parts are >= 2 (take 1 off each of the K parts).
   Exact : array (0 .. 30, 0 .. 30) of Count := [others => [others => 0]];

   --  p (n) by Euler: sum over k >= 1 of (-1) ** (k + 1) times
   --  p (n - k (3k - 1) / 2) + p (n - k (3k + 1) / 2).
   Euler : array (0 .. 30) of Count := [0 => 1, others => 0];

   function Img (V, M : Natural) return String is ("(" & V'Image & "," & M'Image & ")");

   procedure Check_Pair (V, M : Target) is
      Got   : constant Count := Count_Limited (V, M);
      Parts : Count := 0;
   begin
      Report (Got = By_Multiplicity (V, M), "by multiplicity" & Img (V, M));
      for K in 0 .. M loop
         Parts := Parts + Exact (V, K);
      end loop;
      Report (Got = Parts, "conjugate (at most M parts)" & Img (V, M));
      if M >= V then
         Report (Got = Euler (V), "Euler p (V)" & Img (V, M));
      end if;
      case M is
         when 0 => Report (Got = (if V = 0 then 1 else 0), "parts <= 0" & Img (V, M));
         when 1 => Report (Got = 1, "parts <= 1" & Img (V, M));
         when 2 => Report (Got = Count (V / 2 + 1), "parts <= 2" & Img (V, M));
         when 3 => Report (Got = Count (((V + 3) ** 2 + 6) / 12), "parts <= 3" & Img (V, M));
         when others => null;
      end case;
   end Check_Pair;

   Power : Count := 1;
begin
   --  Pow2 regenerated by doubling, entry by entry.
   for E in Exponent loop
      if E > 0 then
         Power := 2 * Power;
      end if;
      pragma Assert (Pow2 (E) = Power);
   end loop;

   Exact (0, 0) := 1;
   for N in 1 .. 30 loop
      for K in 1 .. N loop
         Exact (N, K) := Exact (N - 1, K - 1) + (if N - K >= K then Exact (N - K, K) else 0);
      end loop;
   end loop;

   for N in 1 .. 30 loop
      declare
         K    : Positive := 1;
         Sign : Count := 1;
      begin
         loop
            exit when K * (3 * K - 1) / 2 > N;
            Euler (N) := Euler (N) + Sign * Euler (N - K * (3 * K - 1) / 2);
            if K * (3 * K + 1) / 2 <= N then
               Euler (N) := Euler (N) + Sign * Euler (N - K * (3 * K + 1) / 2);
            end if;
            Sign := -Sign;
            K := K + 1;
         end loop;
      end;
   end loop;

   --  Every (Value, Max_Part) with Value <= 20; above that, the cheap and
   --  the extreme Max_Part values (the run-time contract check of the
   --  ghost P costs grow fast with Value).
   for V in 0 .. 20 loop
      for M in Target loop
         Check_Pair (V, M);
      end loop;
   end loop;
   for V in 21 .. 30 loop
      for M in Target loop
         if M <= 3 or else M = V then
            Check_Pair (V, M);
         end if;
      end loop;
   end loop;
   for V in Target loop
      Report (Count_Combinations (V) = Euler (V), "Count_Combinations = Euler p" & V'Image);
   end loop;

   Ada.Text_IO.Put_Line ("own checks:" & Checked'Image & " checks," & Failures'Image & " failures");
   if Failures > 0 then
      raise Program_Error with "own checks failed";
   end if;
end Own_Checks;
