pragma Ada_2022;
--  Own checks for Combination_Sum_II (see tests/SOURCES.txt). No expected
--  value comes from the program. References:
--  * bitmask enumeration of all subsets of 1 .. Max_Part (Max_Part <= 16);
--  * Euler: distinct-part partitions of n = odd-part partitions of n,
--    counted by multiplicity over the odd parts (any Max_Part >= Value);
--  * complement: a set S of 1 .. C sums to N iff its complement sums to
--    C (C + 1) / 2 - N;
--  * closed forms for Max_Part = 0, 1, 2.
--  The ghost Pow2 table is regenerated by doubling.
with Ada.Text_IO;
with Combination_Sum_II; use Combination_Sum_II;

procedure Own_Checks with SPARK_Mode => Off is
   Failures : Natural := 0;
   Checked  : Natural := 0;

   procedure Report (Ok : Boolean; Label : String) is
   begin
      Checked := Checked + 1;
      if not Ok then
         Failures := Failures + 1;
         if Failures <= 10 then
            Ada.Text_IO.Put_Line ("  FAIL own check: " & Label);
         end if;
      end if;
   end Report;

   function Img (V, M : Natural) return String is ("(" & V'Image & "," & M'Image & ")");

   --  Multisets of odd parts 1, 3, .. <= Largest summing to N: take K
   --  copies of the largest odd part, fill the rest with smaller ones.
   function Odd_Parts (N, Largest : Integer) return Natural is
      Sum : Natural := 0;
   begin
      if Largest < 1 then
         return (if N = 0 then 1 else 0);
      end if;
      for K in 0 .. N / Largest loop
         Sum := Sum + Odd_Parts (N - K * Largest, Largest - 2);
      end loop;
      return Sum;
   end Odd_Parts;

   --  Subset sums of 1 .. C by bitmask, for C <= 16; sums above 30 dropped.
   Mask_Count : array (0 .. 16, Target) of Natural := [others => [others => 0]];

   Power : Long_Long_Integer := 1;
begin
   for E in Target loop
      if E > 0 then
         Power := 2 * Power;
      end if;
      pragma Assert (Long_Long_Integer (Pow2 (E)) = Power);
   end loop;

   for C in 0 .. 16 loop
      for Mask in 0 .. 2 ** C - 1 loop
         declare
            Sum  : Natural := 0;
            Bits : Natural := Mask;
         begin
            for Part in 1 .. C loop
               if Bits mod 2 = 1 then
                  Sum := Sum + Part;
               end if;
               Bits := Bits / 2;
            end loop;
            if Sum <= Target'Last then
               Mask_Count (C, Sum) := Mask_Count (C, Sum) + 1;
            end if;
         end;
      end loop;
   end loop;

   for V in Target loop
      for M in Target loop
         declare
            Got   : constant Natural := Count_Limited (V, M);
            Total : constant Natural := M * (M + 1) / 2;
         begin
            if M <= 16 then
               Report (Got = Mask_Count (M, V), "bitmask" & Img (V, M));
            end if;
            if M >= V then
               Report (Got = Odd_Parts (V, (if V mod 2 = 1 then V else V - 1)),
                       "Euler odd parts" & Img (V, M));
            end if;
            if V <= Total and then Total - V <= Target'Last then
               Report (Got = Count_Limited (Total - V, M), "complement" & Img (V, M));
            elsif V > Total then
               Report (Got = 0, "above 1 + .. + M" & Img (V, M));
            end if;
            case M is
               when 0 => Report (Got = (if V = 0 then 1 else 0), "no parts" & Img (V, M));
               when 1 => Report (Got = (if V <= 1 then 1 else 0), "parts <= 1" & Img (V, M));
               when 2 => Report (Got = (if V <= 3 then 1 else 0), "parts <= 2" & Img (V, M));
               when others => null;
            end case;
         end;
      end loop;
      Report (Count_Distinct_Combinations (V) = Odd_Parts (V, (if V mod 2 = 1 then V else V - 1)),
              "Count_Distinct_Combinations = odd-part count" & V'Image);
   end loop;

   Ada.Text_IO.Put_Line ("own checks:" & Checked'Image & " checks," & Failures'Image & " failures");
   if Failures > 0 then
      raise Program_Error with "own checks failed";
   end if;
end Own_Checks;
