--  Own tests for Flashsort (Sort) (written for this repository; see
--  tests/SOURCES.txt). Assumption: the sort is wrong, loses or invents
--  elements, or does nothing. Expected results come only from two
--  properties of a correct sort, checked independently of how the code
--  sorts: the output is nondecreasing, and every value occurs in the output
--  exactly as often as in the input (occurrence counts, no sorting).
--  The flashsort-specific inputs put keys exactly on, just below and just
--  above the class borders for every class count m = 2 .. 6, cluster all
--  keys in one class, and use the extreme keys Integer'First and
--  Integer'Last (the class map works in Long_Long_Integer).
pragma Ada_2022;
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Environment_Variables;
with Flashsort; use Flashsort;

procedure Own_Checks is
   Failures : Natural := 0;
   Cases    : Natural := 0;
   --  Fixed default seed, printed at start; AA_SEED overrides it.
   subtype Seed_Range is Long_Long_Integer range 1 .. 2_147_483_646;
   Default_Seed : constant Seed_Range := 20_261_008;
   function Initial_Seed return Seed_Range is
     (if Ada.Environment_Variables.Exists ("AA_SEED")
      then Seed_Range'Value (Ada.Environment_Variables.Value ("AA_SEED"))
      else Default_Seed);
   Seed : Long_Long_Integer := Initial_Seed;
   function Next (Lo, Hi : Long_Long_Integer) return Integer is
   begin
      Seed := (Seed * 16_807) mod 2_147_483_647;
      return Integer (Lo + Seed mod (Hi - Lo + 1));
   end Next;

   function Count (A : Element_Array; V : Integer) return Natural is
      N : Natural := 0;
   begin
      for X of A loop
         if X = V then
            N := N + 1;
         end if;
      end loop;
      return N;
   end Count;

   procedure Check_One (Input : Element_Array; Name : String; What : String) is
      A  : Element_Array := Input;
      Ok : Boolean := True;
   begin
      Sort (A);
      for I in A'First .. A'Last - 1 loop
         if A (I) > A (I + 1) then
            Ok := False;
         end if;
      end loop;
      for X of Input loop
         if Count (A, X) /= Count (Input, X) then
            Ok := False;
         end if;
      end loop;
      Cases := Cases + 1;
      if not Ok then
         Failures := Failures + 1;
         if Failures <= 5 then
            Put ("FAIL " & Name & " (" & What & "):");
            for X of Input loop
               Put (X'Image);
            end loop;
            New_Line;
         end if;
      end if;
   end Check_One;

   type Int_List is array (Positive range <>) of Integer;
   Border_Lengths : constant Int_List :=
     [2, 9, 10, 19, 20, 29, 30, 39, 40, 49, 50, 59, 60, 64];
   Border_Gaps    : constant Int_List := [1, 2, 3, 7, 1_000, 2 ** 28];

   procedure Check (Input : Element_Array; What : String) is
   begin
      Check_One (Input, "Sort", What);
   end Check;

begin
   Put_Line ("own checks seed:" & Seed'Image & " (default"
             & Default_Seed'Image & "; set AA_SEED to override)");
   --  1. Every array of length 0 .. 7 over {0, 1, 2} (3,280 arrays: ties, runs).
   for Len in 0 .. 7 loop
      for Code in 0 .. 3 ** Len - 1 loop
         declare
            A : Element_Array (1 .. Len);
         begin
            for I in A'Range loop
               A (I) := (Code / 3 ** (I - 1)) mod 3;
            end loop;
            Check (A, "ternary");
         end;
      end loop;
   end loop;
   --  2. Every permutation of 1 .. 7 (5,040), generated by Heap's method.
   declare
      P : Element_Array (1 .. 7) := [1, 2, 3, 4, 5, 6, 7];
      C : array (1 .. 7) of Natural := [others => 0];
      I : Positive := 2;
      T : Integer;
   begin
      Check (P, "permutation");
      while I <= 7 loop
         if C (I) < I - 1 then
            if I mod 2 = 1 then
               T := P (1); P (1) := P (I); P (I) := T;
            else
               T := P (C (I) + 1); P (C (I) + 1) := P (I); P (I) := T;
            end if;
            Check (P, "permutation");
            C (I) := C (I) + 1;
            I := 2;
         else
            C (I) := 0;
            I := I + 1;
         end if;
      end loop;
   end;
   --  3. Every array of length 0 .. 5 over the extreme values
   --     {Integer'First, -1, 0, 1, Integer'Last} (3,906 arrays).
   declare
      V : constant array (0 .. 4) of Integer :=
        [Integer'First, -1, 0, 1, Integer'Last];
   begin
      for Len in 0 .. 5 loop
         for Code in 0 .. 5 ** Len - 1 loop
            declare
               A : Element_Array (1 .. Len);
            begin
               for I in A'Range loop
                  A (I) := V ((Code / 5 ** (I - 1)) mod 5);
               end loop;
               Check (A, "extreme values");
            end;
         end loop;
      end loop;
   end;
   --  4. Class borders. For each length (class count m = max (2, n / 10))
   --     and gap D: Min = 0, Max = (m - 1) * D, and every other key is a
   --     class border J * D or one off it, in random order.
   for N of Border_Lengths loop
      for D of Border_Gaps loop
         for Rep in 1 .. 2 loop
            declare
               M : constant Positive := Integer'Max (2, N / 10);
               A : Element_Array (1 .. N);
               J : Integer;
            begin
               for I in A'Range loop
                  J := Next (0, Long_Long_Integer (M - 1));
                  A (I) := J * D + (if J = 0 then Next (0, 1)
                                    elsif J = M - 1 then -Next (0, 1)
                                    else Next (-1, 1));
               end loop;
               A (Next (1, Long_Long_Integer (N))) := 0;
               A (Next (1, Long_Long_Integer (N))) := (M - 1) * D;
               Check (A, "class borders n =" & N'Image & " D =" & D'Image);
            end;
         end loop;
      end loop;
   end loop;
   --  5. Random lengths up to Max_N: small range, the whole Integer range,
   --     one class holding all keys but one outlier, two values, keys near
   --     Integer'First / Integer'Last, and a wide signed range.
   for K in 1 .. 200 loop
      declare
         A    : Element_Array (1 .. Next (0, Long_Long_Integer (Max_N)));
         Mode : constant Integer := Next (0, 5);
         Base : constant Integer := Next (-1_000_000, 1_000_000);
      begin
         for I in A'Range loop
            case Mode is
               when 0 => A (I) := Next (0, 9);
               when 1 =>
                  A (I) := Next (Long_Long_Integer (Integer'First),
                                 Long_Long_Integer (Integer'Last));
               when 2 => A (I) := Base + Next (0, 5);
               when 3 => A (I) := (if Next (0, 1) = 0 then Base else -Base);
               when 4 =>
                  A (I) := (if Next (0, 1) = 0 then Integer'First + Next (0, 9)
                            else Integer'Last - Next (0, 9));
               when others => A (I) := Next (-100_000, 100_000);
            end case;
         end loop;
         if Mode = 2 and then A'Length > 0 then
            A (Next (1, Long_Long_Integer (A'Length))) := Integer'Last;
         end if;
         Check (A, "random" & K'Image);
      end;
   end loop;
   --  6. Full length: descending, ascending, all equal, organ pipe, one
   --     outlier at each end of the range.
   declare
      A : Element_Array (1 .. Max_N);
   begin
      A := [for I in A'Range => Max_N - I];
      Check (A, "descending full");
      A := [for I in A'Range => I];
      Check (A, "ascending full");
      A := [for I in A'Range => -777];
      Check (A, "all equal full");
      A := [for I in A'Range => Integer'Min (I, Max_N + 1 - I)];
      Check (A, "organ pipe full");
      A := [others => 5];
      A (Max_N / 2) := Integer'First;
      Check (A, "one low outlier full");
      A := [others => 5];
      A (Max_N / 3) := Integer'Last;
      Check (A, "one high outlier full");
   end;

   if Failures > 0 then
      Put_Line ("FAIL own checks:" & Failures'Image & " of" & Cases'Image);
      raise Program_Error with "own checks failed";
   end if;
   Put_Line ("PASS own checks:" & Cases'Image & " sort calls (nondecreasing + occurrence counts)");
end Own_Checks;
