--  Own tests for Postman_Sort (Sort) (written for this repository; see
--  tests/SOURCES.txt). Assumption: the sort is wrong, loses or invents
--  elements, or does nothing. Expected results come only from two
--  properties of a correct sort, checked independently of how the code
--  sorts: the output is nondecreasing, and every value occurs in the output
--  exactly as often as in the input (occurrence counts, no sorting).
--  Keys are nonnegative (Keys_Ok); the random keys stress digit
--  boundaries (9 / 10, 10**k - 1 / 10**k, 10**9, Integer'Last) and long
--  shared digit prefixes, which drive the MSD recursion. The ghost
--  counting proof also runs under -gnata, so the whole run takes ~10 s.
pragma Ada_2022;
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Environment_Variables;
with Postman_Sort; use Postman_Sort;

procedure Own_Checks is
   Failures : Natural := 0;
   Cases    : Natural := 0;
   --  Fixed default seed, printed at start; AA_SEED overrides it.
   subtype Seed_Range is Long_Long_Integer range 1 .. 2_147_483_646;
   Default_Seed : constant Seed_Range := 20_261_008;
   function Initial_Seed return Seed_Range is
     (if Ada.Environment_Variables.Exists ("AA_SEED")
      then Seed_Range'Value (Ada.Environment_Variables.Value ("AA_SEED"))
      else Default_Seed);
   Seed : Long_Long_Integer := Initial_Seed;
   function Next (Lo, Hi : Long_Long_Integer) return Integer is
   begin
      Seed := (Seed * 16_807) mod 2_147_483_647;
      return Integer (Lo + Seed mod (Hi - Lo + 1));
   end Next;

   function Count (A : Element_Array; V : Integer) return Natural is
      N : Natural := 0;
   begin
      for X of A loop
         if X = V then
            N := N + 1;
         end if;
      end loop;
      return N;
   end Count;

   procedure Check_One (Input : Element_Array; Name : String; What : String) is
      A  : Element_Array := Input;
      Ok : Boolean := True;
   begin
      Sort (A);
      for I in A'First .. A'Last - 1 loop
         if A (I) > A (I + 1) then
            Ok := False;
         end if;
      end loop;
      for X of Input loop
         if Count (A, X) /= Count (Input, X) then
            Ok := False;
         end if;
      end loop;
      Cases := Cases + 1;
      if not Ok then
         Failures := Failures + 1;
         if Failures <= 5 then
            Put ("FAIL " & Name & " (" & What & "):");
            for X of Input loop
               Put (X'Image);
            end loop;
            New_Line;
         end if;
      end if;
   end Check_One;

   procedure Check (Input : Element_Array; What : String) is
   begin
      Check_One (Input, "Sort", What);
   end Check;

begin
   Put_Line ("own checks seed:" & Seed'Image & " (default"
             & Default_Seed'Image & "; set AA_SEED to override)");
   --  1. Every array of length 0 .. 7 over {0, 1, 2} (3,280 arrays: ties, runs).
   for Len in 0 .. 7 loop
      for Code in 0 .. 3 ** Len - 1 loop
         declare
            A : Element_Array (1 .. Len);
         begin
            for I in A'Range loop
               A (I) := (Code / 3 ** (I - 1)) mod 3;
            end loop;
            Check (A, "ternary");
         end;
      end loop;
   end loop;
   --  2. Every permutation of 1 .. 7 (5,040), generated by Heap's method.
   declare
      P : Element_Array (1 .. 7) := [1, 2, 3, 4, 5, 6, 7];
      C : array (1 .. 7) of Natural := [others => 0];
      I : Positive := 2;
      T : Integer;
   begin
      Check (P, "permutation");
      while I <= 7 loop
         if C (I) < I - 1 then
            if I mod 2 = 1 then
               T := P (1); P (1) := P (I); P (I) := T;
            else
               T := P (C (I) + 1); P (C (I) + 1) := P (I); P (I) := T;
            end if;
            Check (P, "permutation");
            C (I) := C (I) + 1;
            I := 2;
         else
            C (I) := 0;
            I := I + 1;
         end if;
      end loop;
   end;
   --  3. Every array of length 0 .. 4 over the digit-boundary values
   --     {0, 9, 10, 99, 100, 10**9, Integer'Last} (2,801 arrays).
   declare
      V : constant array (0 .. 6) of Integer :=
        [0, 9, 10, 99, 100, 1_000_000_000, Integer'Last];
   begin
      for Len in 0 .. 4 loop
         for Code in 0 .. 7 ** Len - 1 loop
            declare
               A : Element_Array (1 .. Len);
            begin
               for I in A'Range loop
                  A (I) := V ((Code / 7 ** (I - 1)) mod 7);
               end loop;
               Check (A, "boundary values");
            end;
         end loop;
      end loop;
   end;
   --  4. Random lengths up to Max_N with nonnegative keys: one digit,
   --     two digits, a shared long prefix, around powers of ten, near
   --     Integer'Last, and the whole range 0 .. Integer'Last.
   for K in 1 .. 800 loop
      declare
         A    : Element_Array (1 .. Next (0, Long_Long_Integer (Max_N)));
         Mode : constant Integer := Next (0, 5);
         Pw   : constant Long_Long_Integer := 10 ** Next (0, 9);
      begin
         for I in A'Range loop
            case Mode is
               when 0 => A (I) := Next (0, 9);
               when 1 => A (I) := Next (0, 99);
               when 2 => A (I) := 123_450_000 + Next (0, 9_999);
               when 3 => A (I) := Integer (Pw) + Next (-1, 1) * Next (0, 1);
               when 4 => A (I) := Integer'Last - Next (0, 25);
               when others => A (I) := Next (0, Long_Long_Integer (Integer'Last));
            end case;
         end loop;
         Check (A, "random" & K'Image);
      end;
   end loop;
   --  5. Full length: descending, ascending, all equal nonzero, powers of
   --     ten in reverse, one large key among zeros.
   declare
      A : Element_Array (1 .. Max_N);
   begin
      A := [for I in A'Range => Max_N - I];
      Check (A, "descending full");
      A := [for I in A'Range => I];
      Check (A, "ascending full");
      A := [for I in A'Range => 777];
      Check (A, "all equal full");
      A := [for I in A'Range => 10 ** ((Max_N - I) mod 10) - (I mod 2)];
      Check (A, "powers of ten full");
      A := [others => 0];
      A (1) := Integer'Last;
      Check (A, "one large key full");
   end;

   if Failures > 0 then
      Put_Line ("FAIL own checks:" & Failures'Image & " of" & Cases'Image);
      raise Program_Error with "own checks failed";
   end if;
   Put_Line ("PASS own checks:" & Cases'Image & " sort calls (nondecreasing + occurrence counts)");
end Own_Checks;
