with Ada.Unchecked_Deallocation;
with Ada.Strings.Fixed;
with Ada.Strings;

package body Abstract_Syntax_Tree is

   procedure Free_Node is new Ada.Unchecked_Deallocation (AST_Node, AST_Node_Access);

   function Create_Literal (Value : Value_Type) return AST_Node_Access is
   begin
      return new AST_Node'(Kind => Kind_Literal, Value => Value);
   end Create_Literal;

   function Create_Variable (Id : Variable_ID) return AST_Node_Access is
   begin
      return new AST_Node'(Kind => Kind_Variable, Id => Id);
   end Create_Variable;

   function Create_Unary (Op : Unary_Op_Kind; Operand : AST_Node_Access) return AST_Node_Access is
   begin
      return new AST_Node'(Kind => Kind_Unary_Op, U_Op => Op, Operand => Operand);
   end Create_Unary;

   function Create_Binary (Op : Binary_Op_Kind; Left, Right : AST_Node_Access) return AST_Node_Access is
   begin
      return new AST_Node'(Kind => Kind_Binary_Op, B_Op => Op, Left => Left, Right => Right);
   end Create_Binary;

   function Evaluate (Node : AST_Node_Access; Env : Environment) return Value_Type is
   begin
      case Node.Kind is
         when Kind_Literal =>
            return Node.Value;
            
         when Kind_Variable =>
            return Env (Node.Id);
            
         when Kind_Unary_Op =>
            declare
               Val : constant Value_Type := Evaluate (Node.Operand, Env);
            begin
               case Node.U_Op is
                  when Op_Neg => return -Val;
               end case;
            end;
            
         when Kind_Binary_Op =>
            declare
               L_Val : constant Value_Type := Evaluate (Node.Left, Env);
               R_Val : constant Value_Type := Evaluate (Node.Right, Env);
            begin
               case Node.B_Op is
                  when Op_Add => return L_Val + R_Val;
                  when Op_Sub => return L_Val - R_Val;
                  when Op_Mul => return L_Val * R_Val;
                  when Op_Div =>
                     if R_Val = 0 then
                        raise Evaluation_Error with "Division by zero in AST";
                     end if;
                     return L_Val / R_Val;
               end case;
            end;
      end case;
   end Evaluate;

   function To_String (Node : AST_Node_Access) return String is
   begin
      case Node.Kind is
         when Kind_Literal =>
            -- Trim spaces generated by integer image attribute
            return Ada.Strings.Fixed.Trim (Value_Type'Image (Node.Value), Ada.Strings.Both);
            
         when Kind_Variable =>
            -- Construct a 1-character string using Ada 2022 bracket syntax
            return [1 => Var_To_Char (Node.Id)];
            
         when Kind_Unary_Op =>
            case Node.U_Op is
               when Op_Neg => 
                  return "(-" & To_String (Node.Operand) & ")";
            end case;
            
         when Kind_Binary_Op =>
            declare
               Op_Str : Character;
            begin
               case Node.B_Op is
                  when Op_Add => Op_Str := '+';
                  when Op_Sub => Op_Str := '-';
                  when Op_Mul => Op_Str := '*';
                  when Op_Div => Op_Str := '/';
               end case;
               return "(" & To_String (Node.Left) & " " & Op_Str & " " & To_String (Node.Right) & ")";
            end;
      end case;
   end To_String;

   function Node_Count (Node : AST_Node_Access) return Positive is
   begin
      case Node.Kind is
         when Kind_Literal | Kind_Variable =>
            return 1;
         when Kind_Unary_Op =>
            return 1 + Node_Count (Node.Operand);
         when Kind_Binary_Op =>
            return 1 + Node_Count (Node.Left) + Node_Count (Node.Right);
      end case;
   end Node_Count;

   function Tree_Depth (Node : AST_Node_Access) return Positive is
   begin
      case Node.Kind is
         when Kind_Literal | Kind_Variable =>
            return 1;
         when Kind_Unary_Op =>
            return 1 + Tree_Depth (Node.Operand);
         when Kind_Binary_Op =>
            return 1 + Positive'Max (Tree_Depth (Node.Left), Tree_Depth (Node.Right));
      end case;
   end Tree_Depth;

   procedure Free_Tree (Node : in out AST_Node_Access) is
   begin
      if Node /= null then
         case Node.Kind is
            when Kind_Literal | Kind_Variable =>
               null; -- No children to free
            when Kind_Unary_Op =>
               Free_Tree (Node.Operand);
            when Kind_Binary_Op =>
               Free_Tree (Node.Left);
               Free_Tree (Node.Right);
         end case;
         Free_Node (Node);
      end if;
   end Free_Tree;

   function Char_To_Var (C : Character) return Variable_ID is
   begin
      if C in 'A' .. 'Z' then
         return Variable_ID (Character'Pos (C) - Character'Pos ('A') + 1);
      else
         return Variable_ID (Character'Pos (C) - Character'Pos ('a') + 1);
      end if;
   end Char_To_Var;

   function Var_To_Char (Id : Variable_ID) return Character is
   begin
      return Character'Val (Integer (Id) - 1 + Character'Pos ('A'));
   end Var_To_Char;

end Abstract_Syntax_Tree;
